# SPDX-FileCopyrightText: 2020 Benedict Harcourt <ben.harcourt@harcourtprogramming.co.uk>
#
# SPDX-License-Identifier: CC0-1.0

name: Linting

on:
  push:
    branches:
      - mainline
      - preview
      - future
  pull_request:
    branches:

jobs:
  build:
    name: Generate Map
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run:  ./make-map.sh

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "[Bot] Regenerate map"
